#spring:
#  application:
#    name: eureka-discovery-service

#server:
#  port: 8083

server :
  port : 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    
#    service-url:
#      defaultZone: http://localhost:8083/eureka